-- 코드를 입력하세요
SELECT HOUR(DATETIME) HOUR,
COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%H:%i') >= '09:00' AND DATE_FORMAT(DATETIME,'%H:%i') <= '19:59'
GROUP BY HOUR
ORDER BY HOUR;