-- 코드를 작성해주세요
-- SCORE가 가장 높은 사원 정보 조회
-- 2022 년도
-- 상반기 하반기 합 =>SCORE
SELECT SUM(B.SCORE) SCORE,
B.EMP_NO,
A.EMP_NAME,
A.POSITION,
A.EMAIL
FROM HR_EMPLOYEES A 
JOIN HR_GRADE B
ON A.EMP_NO = B.EMP_NO
GROUP BY B.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;